#!/bin/bash
#
# refresh-guest-status -- handle
#
# The arguments sent to the script are "add" or "del",
# then the MAC address, the IP address and finally the hostname
# if there is one.
#
# --> we don't mind the argument as we update the whole anyway

# nef_command_name=refresh-guest-status

log=/var/log/refresh-guest-status.log
echo $(date) -- "$@" >>$log

_log() {
    echo $(date) "$@" >>$log
}

# usage: _resolve_host <host>
_resolve_host() {
    local _host="$1"
    local _ip

    if [[ $_host =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        _ip=$_host

    elif [ -d "/sys/class/net/$_host" ]; then
        _ip=$_host

    elif [[ $_host =~ \.lxc$ ]]; then
        local _lxc_name=$(echo "$_host" | sed 's/\.lxc$//')
        _ip=$(lxc-info -i -H -n "$_lxc_name")
        if [ $? -ne 0 ]; then
            _log "Warning: LXC container is not running or does not have an IP: $_lxc_name"
            return 1
        fi
    else
        _ip=$(getent ahostsv4 "$_host" | grep STREAM | grep -v ^127.0. | head -n 1 | cut -d ' ' -f 1)
        if [ -z "$_ip" ]; then
            _log "Warning: could not resolve host: $_host"
            return 1
        fi
    fi

    echo $_ip
}

cat /etc/metagitted/ipv4.forward.tab | grep -v '^ *#' | grep -v '^ *$' | (
    while read; do
        src=$(echo "$REPLY" | cut -d' ' -f1)
        dest=$(echo "$REPLY" | cut -d' ' -f2)
        echo Redirect from $src to $dest >>$log
        src_host=$(echo "$src" | cut -d: -f1)
        src_port=$(echo "$src" | cut -d: -f2)
        dest_host=$(echo "$dest" | cut -d: -f1)
        dest_port=$(echo "$dest" | cut -d: -f2)

        if [ "$src_host" != "*" ]; then
            src_ip=$(_resolve_host "$src_host")
            [ $? -eq 0 ] || continue
        fi
        protocol=$(echo "$src_port" | cut -d/ -f2)
        src_port=$(echo "$src_port" | cut -d/ -f1)

        dest_ip=$(_resolve_host "$dest_host")
        [ $? -eq 0 ] || continue
        echo "Forward $protocol from $src_host:$src_port (IP=$src_ip) to $dest_host:$dest_port (IP=$dest_ip)" >>$log

        chain="PREROUTING"
        filter="-A PREROUTING"
        if [ -d "/sys/class/net/$src_host" ]; then
            chain="$chain -i $src_host"
            filter="$filter.* -i $src_host"
        elif [ "$src_host" != "*" ]; then
            chain="$chain -d $src_ip"
            filter="$filter.* -d $src_ip"
        fi
        chain="$chain -p $protocol --dport $dest_port -j DNAT --to $dest_ip:$dest_port"
        filter="$filter.* -p $protocol.* --dport $dest_port"

        _log "filter: $filter"
        iptables -t nat -S PREROUTING | grep "^-A " | cat -n  >> $log
        old_rule=$(iptables -t nat -S PREROUTING | grep "^-A " | cat -n | grep -E -- "$filter" | head -n 1 | sed -r 's/^ *([0-9]+).*/\1/')
        if [ -n "$old_rule" ]; then
            _log "OLD RULE NUMBER: $old_rule"
            iptables -t nat -D PREROUTING $old_rule
        fi

        # -i eth0 -p tcp -m tcp --dport 80

        _log iptables -t nat -A $chain
        iptables -t nat -A $chain

        # iptables -t nat --line-numbers -n -L PREROUTING | grep " tcp dpt:80 to:"
        # PREROUTING -p tcp --dport 8080 -j DNAT --to IP:8080
    done
)
# iptables -t nat -A lxc-nat -d #{src_ip} -p tcp --dport #{src_port} -j DNAT --to #{containers[lxc_name]}:#{lxc_port}
# iptables -t nat -F lxc-nat
# iptables -t nat -D PREROUTING -j lxc-nat
# iptables -t nat -X lxc-nat
