#!/bin/bash
#
# JFG 20140225 - Depends on lxc-debian
#
# Examples:
#   lxc-create -n test -t nef-sysconf -- <sysconf-profile-1> <sysconf-profile-2> ...
#   lxc-create -n test -t nef-sysconf   # will install "sysconf.nef.common" by default
#

configure_sysconf()
{
    path=$1
    rootfs=$2
    hostname=$3
    shift
shift
shift

#     [ -d $rootfs/root/.ssh ] || mkdir $rootfs/root/.ssh
#     sshPubKeyPath=~/.ssh/id_dsa.pub
#     [ -r $sshPubKeyPath ] && {
#         authorizedPath=$rootfs/root/.ssh/authorized_keys
#         echo "Adding key '$sshPubKeyPath' to $authorizedPath"
#         cat $sshPubKeyPath >>$authorizedPath
#     }
#     cat <<EOF >>$rootfs/root/.ssh/config
# Host git.geonef.fr
# Port 4286
# User okapi
# EOF

    profiles=( "$@" )
    [ "${#profiles[@]}" -gt 0 ] && profiles=(sysconf.nef.common)

    sysconf_setup=_sysconf-setup.sh
    sysconfRemoteBase=https://github.com/geonef/

    echo "Installing sysconf..."
    mkdir -p $rootfs/sysconf/actual
    for profile in "${profiles[@]}"; do
        echo " profile: $profile"
        echo $profile >>$rootfs/sysconf/actual/deps
        cd $rootfs/sysconf/
        git clone $sysconfRemoteBase/$profile.git
    done

    echo $sysconfRemoteBase >$rootfs/sysconf/repository_root
    SYSCONF_PATH=$rootfs/sysconf sysconf fetch

    chroot $rootfs /sysconf/sysconf.base/tree/usr/bin/sysconf compile install

    return $?
}


. /usr/share/lxc/templates/lxc-debian

[ "$1" = "" ] && {
    echo "sysconf name(s) required"
    exit 1
}

configure_sysconf $path $rootfs $name "$@"
if [ $? -ne 0 ]; then
    echo "failed to configure sysconf"
    exit 1
fi

exit 0
