#!/bin/bash
#

. /usr/share/gitted/shell-driver || exit 2

gitted_driver_list() {
    local _ifs="$IFS"; IFS=",$IFS"
    local _list=($GITTED_CONFIG_DUMMY_NESTEDBRANCHES); IFS="$_ifs"

    for _item in "${_list[@]}"; do
        echo "$_item"
    done
}
gitted_driver_status_code() {

    local _status=$GITTED_CONFIG_DUMMY_STATUS
    if [ -n "$GITTED_CONFIG_STATE_BRANCH" ]; then
        local _var=GITTED_CONFIG_DUMMY_${GITTED_CONFIG_STATE_BRANCH_UC}_STATUS
        # echo "dummy var = $_var" >&2
        if [ -n "${!_var}" ]; then
            _status=${!_var}
        fi
    else
        _status=1
    fi
    return $_status
}

gitted_driver_commit() {
    return 2 # nothing to commit
}


gitted_driver_run "$@"
